### ISSUE TITLE
Leanpub not free by default anymore

### ISSUE THREAD

**Issue by oscard0m** [nickfloyd/NerdLifeBalance#5]
The book is not possible to be purchased for free anymore unless the author opts out of a revenue pool.

The subscription requirement should be updated or the README.md explaining accordingly.

More info here: 
- https://leanpub.com/imagine_a_world
- https://github.com/EbookFoundation/free-programming-books/issues/6852

**Comment by nickfloyd** [comment]
@oscard0m Solid call out... I just now saw this today... I think I'll publish the PDF to this repo.  Thanks for the heads up.  Sorry it took me so long to catch it.

**Comment by nickfloyd** [comment]
Fixed with: https://github.com/nickfloyd/NerdLifeBalance/tree/master/rendered_book

**Comment by oscard0m** [comment]
Thanks for sharing!
